# Generated by Django 2.1.5 on 2019-01-30 22:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20190130_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='greeting',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
