# Generated by Django 2.1.5 on 2019-01-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190130_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='greeting',
            field=models.CharField(max_length=200),
        ),
    ]
