# Generated by Django 2.2 on 2019-04-03 22:15

from django.db import migrations, models

def roll_forward(apps, schema_editor):
    Greeting = apps.get_model("data", "Greeting")
    for greeting in Greeting.objects.using(schema_editor.connection.alias):
        greeting.punctuation = greeting.greeting[-1] # Place existing punctuation
        greeting.greeting = greeting.greeting[:-1] # Remove existing punctuation
        greeting.save()

def roll_back(apps, schema_editor):
    Greeting = apps.get_model("data", "Greeting")
    for greeting in Greeting.objects.using(schema_editor.connection.alias):
        # Replace punctuation
        greeting.greeting = greeting.greeting +  greeting.punctuation 
        greeting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20190130_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='punctuation',
            field=models.CharField(default='.', max_length=1),
        ),
        migrations.RunPython(roll_forward, roll_back)
    ]
